# Generated by Django 4.0.2 on 2023-03-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('amenity_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('roomtype', models.CharField(max_length=200)),
                ('amen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('meal', models.IntegerField(verbose_name=200)),
                ('parking', models.IntegerField(verbose_name=200)),
                ('taxcharge', models.IntegerField(verbose_name=200)),
                ('total', models.IntegerField(verbose_name=200)),
                ('roomprice', models.IntegerField(verbose_name=200)),
                ('hotelname', models.CharField(max_length=200)),
                ('checkin_date', models.DateField(null=True)),
                ('checkout_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_details',
            fields=[
                ('hotel_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('guest_rating', models.IntegerField(verbose_name=200)),
                ('total_room', models.IntegerField(verbose_name=6000)),
                ('price', models.IntegerField(verbose_name=2000)),
            ],
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('tax_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('tax_rate', models.IntegerField(verbose_name=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='udetails',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('name_on_card', models.CharField(max_length=200)),
                ('cc_number', models.CharField(max_length=200)),
                ('exp_month', models.CharField(max_length=200)),
                ('exp_yr', models.IntegerField(verbose_name=200)),
                ('cvv', models.IntegerField(verbose_name=200)),
            ],
        ),
        migrations.CreateModel(
            name='room_d',
            fields=[
                ('room_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Sleeps', models.IntegerField(verbose_name=200)),
                ('bedtype', models.CharField(max_length=200)),
                ('classtype', models.CharField(max_length=200)),
                ('sqft', models.CharField(max_length=200)),
                ('room_price', models.IntegerField(verbose_name=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel_details')),
            ],
        ),
        migrations.CreateModel(
            name='extra',
            fields=[
                ('extra_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('meals', models.IntegerField(verbose_name=200)),
                ('parking', models.IntegerField(verbose_name=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel_details')),
            ],
        ),
    ]
