# Generated by Django 4.0.2 on 2023-03-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
    ]
