# Generated by Django 4.0.2 on 2023-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_details',
            fields=[
                ('flight_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.IntegerField(verbose_name=200)),
                ('airline', models.CharField(max_length=200)),
                ('depart_city', models.CharField(max_length=200)),
                ('arrival_city', models.CharField(max_length=200)),
                ('depart_time', models.DateField(null=True)),
                ('arrival_time', models.DateField(null=True)),
                ('price', models.IntegerField(verbose_name=2000)),
            ],
        ),
    ]
