# Generated by Django 4.0.2 on 2023-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cancel_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_details',
            name='total_room',
            field=models.IntegerField(null=True),
        ),
    ]
