# Generated by Django 4.0.2 on 2023-04-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_flightudetails_flightbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_flightbooking',
            fields=[
                ('cancel_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(verbose_name=200)),
                ('user_id', models.IntegerField(verbose_name=200)),
                ('uname', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('name_on_card', models.CharField(max_length=200)),
                ('cc_number', models.CharField(max_length=200)),
                ('exp_month', models.CharField(max_length=200)),
                ('exp_yr', models.IntegerField(verbose_name=200)),
                ('cvv', models.IntegerField(verbose_name=200)),
                ('destcity', models.CharField(max_length=200)),
                ('arrivalcity', models.CharField(max_length=200)),
                ('flightprice', models.IntegerField(verbose_name=200)),
                ('airline', models.CharField(max_length=200)),
                ('destdate', models.DateField(null=True)),
                ('arrivaldate', models.DateField(null=True)),
            ],
        ),
    ]
