# Generated by Django 4.0.2 on 2023-04-19 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cancel_flightbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_booking',
            name='hotel_bookin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking', unique=True),
        ),
    ]
